
theme {
    style = Breeze
    color_scheme = /usr/share/color-schemes/BreezeDark.colors
    icon_theme = Tela-blue-dark
    
    # Updated Font Settings
    font = JetBrainsMono Nerd Font
    font_size = 11
    
    # Optional: Set as fixed-width font for specific widgets
    font_fixed = JetBrainsMono Nerd Font Mono
    font_fixed_size = 11
}
