# preload = /home/dickhead/Pictures/wallpapers/wallpaper5.jpg

# Set the wallpaper for your specific monitor
# wallpaper = ,/home/dickhead/Pictures/wallpapers/wallpaper5.jpg

preload = /home/dickhead/Pictures/wallpapers/wallpaper8.png

wallpaper {
    monitor = 
    path = /home/dickhead/Pictures/wallpapers/wallpaper8.png
}
